entvirt/script/proyecto/app/urls.py
from django.urls import path
from .views import hola_mundo, CategoriaListar, CategoriaNueva, CategoriaEditar, CategoriaBorrar, \
    SubCategoriaListar, subCategoriaNueva

urlpatterns = [
    path("hola-mundo", hola_mundo, name="home1"),
    path("categorias/", CategoriaListar.as_view(), name="categoria_listar"),
    path("categorias/nueva/", CategoriaNueva.as_view(), name="categoria_nueva"),
    path("categorias/editar/<int:pk>", CategoriaEditar.as_view(), name="categoria_editar"),
    path("categorias/borrar/<int:pk>", CategoriaBorrar.as_view(), name="categoria_borrar"),

    path("sub-categorias/", SubCategoriaListar.as_view(), name="subcategoria_listar"),
    path("sub-categorias/nueva", subCategoriaNueva.as_view(), name="subcategoria_nueva"),
]

entvirt/script/proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("app/",include(('app.urls','app'),namespace='app')),
    path('admin/', admin.site.urls),
]

entvirt/script/proyecto/app/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    descripcion = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        unique=True
    )

    def __str__(self):
        return "{}".format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria,self).save()

    class Meta:
        verbose_name_plural="Categorias"
    
class SubCategoria(models.Model):
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=50,
        blank=False,
        null=False
    )

    def __str__(self):
        return "{} --> {}".format(self.categoria, self.descripcion)
    
    class Meta:
        verbose_name_plural = "Sub Categorias"

entvirt/script/proyecto/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from app.models import Categoria, SubCategoria
from django.urls import reverse_lazy
from .form import CategoriaForm, SubCategoriaForm


#Asi tambien se puede importar la categoria
#from .models import Categoria

# Create your views here.
def hola_mundo(request):
    return HttpResponse("Hola Mundo")

#vista basadas en funcions y vistas basadas en clase

class  CategoriaListar(generic.ListView):
    model=Categoria
    template_name='app/categoria_list.html'
    context_object_name='obj' # es el nombre del objeto de la consulta
    ordering="descripcion"

class CategoriaNueva(generic.CreateView):
    model=Categoria
    template_name='app/categoria_form.html'
    context_object_name='obj' # es el nombre del objeto de la consulta
    form_class=CategoriaForm
    success_url=reverse_lazy('app:categoria_listar')

class CategoriaEditar(generic.UpdateView):
    model=Categoria
    template_name='app/categoria_form.html'
    context_object_name='obj' # es el nombre del objeto de la consulta
    form_class=CategoriaForm
    success_url=reverse_lazy('app:categoria_listar')

class CategoriaBorrar(generic.DeleteView):
    model=Categoria
    template_name='app/borrar.html'
    context_object_name='obj' # es el nombre del objeto de la consulta
    form_class=CategoriaForm
    success_url=reverse_lazy('app:categoria_borrar')    

class  SubCategoriaListar(generic.ListView):
    model=SubCategoria
    template_name='app/subcategoria_list.html'
    context_object_name='obj' # es el nombre del objeto de la consulta

class subCategoriaNueva(generic.CreateView):
    model=SubCategoria
    template_name='app/subcategoria_form.html'
    context_object_name='obj' # es el nombre del objeto de la consulta
    form_class=SubCategoriaForm
    success_url=reverse_lazy('app:subcategoria_listar')

entvirt/script/proyecto/app/templates/app/borrar.html
{% extends 'base/index.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Confirma</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        <h3>¿Borrar {{ obj.descripcion }}?</h3>
        <button type="submit" class="btn btn-danger" >Si, Borrar</button>
        <a href="{% url 'app:categoria_listar' %}" class="btn btn-info">No, Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto/app/templates/app/categoria_form.html
{% extends 'base/index.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Agregar Categoria</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" >Save</button>
        <a href="{% url 'app:categoria_listar' %}" class="btn btn-primary">Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto/app/templates/app/categoria_list.html
{% extends 'base/index.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 30rem;">
    <div class="card-header">Listado de Categorias <a href="{% url 'app:categoria_nueva' %}" class="btn btn-primary">Nueva</a></div>
    <div class="card-body">
        <table class="table table-hover">
          <thead>
              <th>Id</th>
              <th>Descripcion</th>
              <th>Accion</th>              
          </thead>
          <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.descripcion }}</td>             
                <td><a href="{% url 'app:categoria_editar' item.id %}" class="btn btn-warning">Editar</a>
                  <a href="{% url 'app:categoria_borrar' item.id %}" class="btn btn-danger">Borrar</a>
                </td>
        </tr>
        {% endfor %}        
          </tbody>
      </table>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto/app/templates/app/subcategoria_form.html
{% extends 'base/index.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Agregar Sub Categoria</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" >Save</button>
        <a href="{% url 'app:subcategoria_listar' %}" class="btn btn-primary">Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto/app/templates/app/subcategoria_list.html
{% extends 'base/index.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 30rem;">
    <div class="card-header">Listado de sub Categorias<a href="{% url 'app:subcategoria_nueva' %}" class="btn btn-primary">Nueva</a> </div>
    <div class="card-body">
        <table class="table table-hover">
          <thead>
              <th>Id</th>
              <th>Categoria</th>
              <th>Descripcion</th>              
              <th>Acciones</th>
          </thead>
          <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.categoria }}</td>                             
                <td>{{ item.descripcion }}</td>             
                <td><!-- <a href="{% url 'app:categoria_editar' item.id %}" class="btn btn-warning">Editar</a>
                  <a href="{% url 'app:categoria_borrar' item.id %}" class="btn btn-danger">Borrar</a> -->
                </td>
        </tr>
        {% endfor %}        
          </tbody>
      </table>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto/templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Primer Proyecto</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:categoria_listar' %}">Categorias</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app:categoria_nueva' %}">New Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


    {% block contenido %}
    {% endblock %}

    {% block piePagina %}
     Mi pie de Pagina
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
</body>
</html>