entvirt/script/proyecto_tarea/cha_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include
from .views import VendedorListar, VendedorNueva, VendedorBorrar, VendedorEditar, PolizaListar, PolizaNueva \
    , HospitalListar, HospitalNuevo, HospitalEditar, HospitalBorrar, AseguradoNuevo, AseguradoEditar, AseguradoBorrar, \
    AseguradoListar, PolizaEditar, PolizaBorrar, index, ContratoPoliza, ContratoPolizaListar, home, TemplateSinPrivilegio, \
    DoctorNuevo, DoctorBorrar, DoctorEditar, DoctorListar, FamiliaresBorrar, FamiliaresEditar, FamiliaresListar, \
    FamiliaresNuevo, HospitalizacionNuevo, HospitalizacionBorrar, HospitalizacionListar, HospitalizacionEditar, \
    TratamientoNuevo, TratamientoBorrar, TratamientoEditar, TratamientoListar, DetalleTratamientoNuevo, \
    DetalleTratamientoBorrar, DetalleTratamientoEditar, DetalleTratamientoListar, AseguradoFamiliarLista, ContratoPolizaEditar, \
    ContratoPolizaBorrar
from .reportes import reporte_vendedores, reporte_contrato

urlpatterns = [
    path('home', home, name='home'),
    path("vendedores/", VendedorListar.as_view(), name="vendedor_listar"),
    path("vendedores/nuevo/", VendedorNueva.as_view(), name="vendedor_nuevo"),
    path("vendedores/editar/<int:pk>", VendedorEditar.as_view(), name="vendedor_editar"),
    path("vendedores/borrar/<int:pk>", VendedorBorrar.as_view(), name="vendedor_borrar"),

    path("polizas/", PolizaListar.as_view(), name="poliza_listar"),
    path("polizas/nuevo/", PolizaNueva.as_view(), name="poliza_nuevo"),
    path("polizas/editar/<int:pk>", PolizaEditar.as_view(), name="poliza_editar"),
    path("polizas/borrar/<int:pk>", PolizaBorrar.as_view(), name="poliza_borrar"),

    path("hospitales/", HospitalListar.as_view(), name="hospital_listar"),
    path("hospitales/nuevo/", HospitalNuevo.as_view(), name="hospital_nuevo"),
    path("hospitales/editar/<int:pk>", HospitalEditar.as_view(), name="hospital_editar"),
    path("hospitales/borrar/<int:pk>", HospitalBorrar.as_view(), name="hospital_borrar"),

    path("asegurados/nuevo/", AseguradoNuevo.as_view(), name="asegurado_nuevo"),
    path("asegurados/editar/<int:pk>", AseguradoEditar.as_view(), name="asegurado_editar"),
    path("asegurados/borrar/<int:pk>", AseguradoBorrar.as_view(), name="asegurado_borrar"),
    path("asegurados/", AseguradoListar.as_view(), name="asegurado_listar"),

    # path("", views.loginpage, name="loginpage"),
    # path("login/", views.loginpage, name="loginpage"),
    path("", auth_views.LoginView.as_view(template_name='cha_app/login.html'), name="login"),
    path("", auth_views.LogoutView.as_view(template_name='cha_app/login.html'), name="logout"),
    path('sin_privilegios/', TemplateSinPrivilegio.as_view(), name='sin_privilegios'),
    # path("login/", auth_views.LoginView.as_view(template_name='cha_app/login.html'), name="login"),
    path("contratos/", ContratoPolizaListar.as_view(), name="contrato_listar"),
    path("contratos/nuevo/", ContratoPoliza.as_view(), name="contrato_nuevo"),
    path("contratos/editar/<int:pk>", ContratoPolizaEditar.as_view(), name="contrato_editar"),
    path("contratos/borrar/<int:pk>", ContratoPolizaBorrar.as_view(), name="contrato_borrar"),

    path("doctor/nuevo/", DoctorNuevo.as_view(), name="doctor_nuevo"),
    path("doctor/editar/<int:pk>", DoctorEditar.as_view(), name="doctor_editar"),
    path("doctor/borrar/<int:pk>", DoctorBorrar.as_view(), name="doctor_borrar"),
    path("doctor/", DoctorListar.as_view(), name="doctor_listar"),

    path("familiares/nuevo/<int:id>", FamiliaresNuevo.as_view(), name="familiares_nuevo"),
    path("familiares/editar/<int:pk>", FamiliaresEditar.as_view(), name="familiares_editar"),
    path("familiares/borrar/<int:pk>", FamiliaresBorrar.as_view(), name="familiares_borrar"),
    path("familiares/", AseguradoFamiliarLista.as_view(), name="familiares_listar"),
    path("familiares/listar/<int:id>", FamiliaresListar.as_view(), name="familiares_asegurado_listar"),

    path("reportes/vendedores/", reporte_vendedores, name='vendedores_print_all'),
    path("reportes/contratos/<int:id>", reporte_contrato, name='contrato_print'),

    path("hospitalizaciones/nuevo/", HospitalizacionNuevo.as_view(), name="hospitalizaciones_nuevo"),
    path("hospitalizaciones/editar/<int:pk>", HospitalizacionEditar.as_view(), name="hospitalizaciones_editar"),
    path("hospitalizaciones/borrar/<int:pk>", HospitalizacionBorrar.as_view(), name="hospitalizaciones_borrar"),
    path("hospitalizaciones/", HospitalizacionListar.as_view(), name="hospitalizaciones_listar"),

    path("tratamientos/nuevo/", TratamientoNuevo.as_view(), name="tratamiento_nuevo"),
    path("tratamientos/editar/<int:pk>", TratamientoEditar.as_view(), name="tratamiento_editar"),
    path("tratamientos/borrar/<int:pk>", TratamientoBorrar.as_view(), name="tratamiento_borrar"),
    path("tratamientos/", TratamientoListar.as_view(), name="tratamiento_listar"),


    path("detalletratamientos/nuevo/<int:id>", DetalleTratamientoNuevo.as_view(), name="detalletratamiento_nuevo"),
    path("detalletratamientos/editar/<int:pk>", DetalleTratamientoEditar.as_view(), name="detalletratamiento_editar"),
    path("detalletratamientos/borrar/<int:pk>", DetalleTratamientoBorrar.as_view(), name="detalletratamiento_borrar"),
    path("detalletratamientos/listar/<int:id>", DetalleTratamientoListar.as_view(), name="detalletratamiento_listar"),
]

entvirt/script/proyecto_tarea/proyecto_tarea/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cha_app/", include(('cha_app.urls', 'app'), namespace='cha_app')),
]

entvirt/script/proyecto_tarea/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Control de Hospitalizacion de Asegurados</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/fontAwesone/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/dataTables.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">SISTEMA DE CONTROL DE POLIZAS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Inicio<span class="sr-only">(current)</span></a>
            </li>
              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-archive"></i> Catalogos</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'cha_app:vendedor_listar' %}"><i class="fa fa-child"></i> Vendedores</a>
                      <a class="dropdown-item" href="{% url 'cha_app:poliza_listar' %}"><i class="fa fa-address-card"></i> Polizas</a>
                      <a class="dropdown-item" href="{% url 'cha_app:hospital_listar' %}"><i class="fa fa-hospital"></i> Hospitales</a>
                      <a class="dropdown-item" href="{% url 'cha_app:doctor_listar' %}"><i class="fa fa-user-md"></i> Médicos</a>
                      <a class="dropdown-item" href="{% url 'cha_app:tratamiento_listar' %}"><i class="fa fa-user-md"></i> Tratamientos</a>
                     <!-- <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Separated link</a> -->
                    </div>
              </li>

            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-heartbeat"></i> Contratar Poliza</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'cha_app:asegurado_nuevo' %}"><i class="fa fa-street-view"></i> Registrar Asegurado</a>
                      <a class="dropdown-item" href="{% url 'cha_app:contrato_nuevo' %}"><i class="fa fa-edit"></i> Registrar Contrato</a>

                     <!-- <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Separated link</a> -->
                    </div>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cha_app:familiares_listar' %}"><i class="fa fa-female"></i> Familiares</a>

            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cha_app:hospitalizaciones_listar' %}"><i class="fa fa-ambulance"></i> Hospitalizacion</a>
            </li>
            <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-clone"></i> Reportes</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'cha_app:vendedores_print_all' %}" TARGET="reportes"><i class="fa fa-child"></i> Vendedores</a>
                    </div>
              </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'cha_app:logout' %}"><i class="fa fa-power-off"></i> Salir</a>
            </li>
          </ul>

        </div>
      </nav>

<div class="jumbotron">
    {% block contenido %}
    {% endblock %}
</div>
<di class="fixed-bottom">
    {% block piePagina %}
     <div class="row bg-primary">
         <div class="col-lg-12">
              <div class="text-capitalize text-lg-center text-white">
                  Derechos Reservados 2020.
              </div>
         </div>
     </div>
    {% endblock %}
</di>



    <script src="{% static 'base/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <!-- <script src="{% static 'base/js/dataTables.bootstrap4.min.js' %}"></script> -->
    <script src="{% static 'base/js/jquery.dataTables.min.js' %}"></script>
</body>

{% block js_page %}
{% endblock %}
</html>

entvirt/script/proyecto_tarea/templates/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Control de Hospitalizacion de Asegurados</title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/fontAwesone/css/all.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">SISTEMA DE CONTROL DE HOSPITALIZACION</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      </nav>

<div >
    {% block login %}
    {% endblock %}
</div>
<di class="fixed-bottom">
    {% block piePagina %}
     <div class="row bg-primary">
         <div class="col-lg-12">
              <div class="text-capitalize text-lg-center text-white">
                  Derechos Reservados 2020.
              </div>
         </div>
     </div>
    {% endblock %}
</di>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
</body>
</html>

entvirt/script/proyecto_tarea/templates/base/login.html
{% extends 'base/index.html' %}
{% block login %}
{% endblock %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form class="box" method="post">
                    <h1>Login</h1>
                    <p class="text-muted"> Please enter your login and password!</p> <input type="text" name=""
                                                                                            placeholder="Username">
                    <input type="password" name="" placeholder="Password"> <a class="forgot text-muted" href="#">Forgot
                    password?</a> <input type="submit" name="" value="Login" href="#">
                </form>
            </div>
        </div>
    </div>
</div>

entvirt/script/proyecto_tarea/templates/base/sin_permisos.html
{% extends 'base/home.html' %}

{% block contenido %}
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4 class="alert-heading">Warning!</h4>
  <p class="mb-0">Estimado Usuario  {{ user.get_full_name }} ({{ user.username}}) no dispones de los permisos necesarios para hacer uso de esta opcion <a href="#" class="alert-link">Salir</a>.</p>
</div>
{% endblock %}