entvirt/script/proyecto_tarea/cha_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include
from .views import VendedorListar, VendedorNueva, VendedorBorrar, VendedorEditar, PolizaListar, PolizaNueva \
    , HospitalListar, HospitalNuevo, HospitalEditar, HospitalBorrar, AseguradoNuevo, AseguradoEditar, AseguradoBorrar, \
    AseguradoListar, PolizaEditar, PolizaBorrar, index, ContratoPoliza, ContratoPolizaListar, home, TemplateSinPrivilegio, \
    DoctorNuevo, DoctorBorrar, DoctorEditar, DoctorListar, FamiliaresBorrar, FamiliaresEditar, FamiliaresListar, \
    FamiliaresNuevo, HospitalizacionNuevo, HospitalizacionBorrar, HospitalizacionListar, HospitalizacionEditar, \
    TratamientoNuevo, TratamientoBorrar, TratamientoEditar, TratamientoListar, DetalleTratamientoNuevo, \
    DetalleTratamientoBorrar, DetalleTratamientoEditar, DetalleTratamientoListar, AseguradoFamiliarLista, ContratoPolizaEditar, \
    ContratoPolizaBorrar
from .reportes import reporte_vendedores, reporte_contrato

urlpatterns = [
    path('home', home, name='home'),
    path("vendedores/", VendedorListar.as_view(), name="vendedor_listar"),
    path("vendedores/nuevo/", VendedorNueva.as_view(), name="vendedor_nuevo"),
    path("vendedores/editar/<int:pk>", VendedorEditar.as_view(), name="vendedor_editar"),
    path("vendedores/borrar/<int:pk>", VendedorBorrar.as_view(), name="vendedor_borrar"),

    path("polizas/", PolizaListar.as_view(), name="poliza_listar"),
    path("polizas/nuevo/", PolizaNueva.as_view(), name="poliza_nuevo"),
    path("polizas/editar/<int:pk>", PolizaEditar.as_view(), name="poliza_editar"),
    path("polizas/borrar/<int:pk>", PolizaBorrar.as_view(), name="poliza_borrar"),

    path("hospitales/", HospitalListar.as_view(), name="hospital_listar"),
    path("hospitales/nuevo/", HospitalNuevo.as_view(), name="hospital_nuevo"),
    path("hospitales/editar/<int:pk>", HospitalEditar.as_view(), name="hospital_editar"),
    path("hospitales/borrar/<int:pk>", HospitalBorrar.as_view(), name="hospital_borrar"),

    path("asegurados/nuevo/", AseguradoNuevo.as_view(), name="asegurado_nuevo"),
    path("asegurados/editar/<int:pk>", AseguradoEditar.as_view(), name="asegurado_editar"),
    path("asegurados/borrar/<int:pk>", AseguradoBorrar.as_view(), name="asegurado_borrar"),
    path("asegurados/", AseguradoListar.as_view(), name="asegurado_listar"),

    # path("", views.loginpage, name="loginpage"),
    # path("login/", views.loginpage, name="loginpage"),
    path("", auth_views.LoginView.as_view(template_name='cha_app/login.html'), name="login"),
    path("", auth_views.LogoutView.as_view(template_name='cha_app/login.html'), name="logout"),
    path('sin_privilegios/', TemplateSinPrivilegio.as_view(), name='sin_privilegios'),
    # path("login/", auth_views.LoginView.as_view(template_name='cha_app/login.html'), name="login"),
    path("contratos/", ContratoPolizaListar.as_view(), name="contrato_listar"),
    path("contratos/nuevo/", ContratoPoliza.as_view(), name="contrato_nuevo"),
    path("contratos/editar/<int:pk>", ContratoPolizaEditar.as_view(), name="contrato_editar"),
    path("contratos/borrar/<int:pk>", ContratoPolizaBorrar.as_view(), name="contrato_borrar"),

    path("doctor/nuevo/", DoctorNuevo.as_view(), name="doctor_nuevo"),
    path("doctor/editar/<int:pk>", DoctorEditar.as_view(), name="doctor_editar"),
    path("doctor/borrar/<int:pk>", DoctorBorrar.as_view(), name="doctor_borrar"),
    path("doctor/", DoctorListar.as_view(), name="doctor_listar"),

    path("familiares/nuevo/<int:id>", FamiliaresNuevo.as_view(), name="familiares_nuevo"),
    path("familiares/editar/<int:pk>", FamiliaresEditar.as_view(), name="familiares_editar"),
    path("familiares/borrar/<int:pk>", FamiliaresBorrar.as_view(), name="familiares_borrar"),
    path("familiares/", AseguradoFamiliarLista.as_view(), name="familiares_listar"),
    path("familiares/listar/<int:id>", FamiliaresListar.as_view(), name="familiares_asegurado_listar"),

    path("reportes/vendedores/", reporte_vendedores, name='vendedores_print_all'),
    path("reportes/contratos/<int:id>", reporte_contrato, name='contrato_print'),

    path("hospitalizaciones/nuevo/", HospitalizacionNuevo.as_view(), name="hospitalizaciones_nuevo"),
    path("hospitalizaciones/editar/<int:pk>", HospitalizacionEditar.as_view(), name="hospitalizaciones_editar"),
    path("hospitalizaciones/borrar/<int:pk>", HospitalizacionBorrar.as_view(), name="hospitalizaciones_borrar"),
    path("hospitalizaciones/", HospitalizacionListar.as_view(), name="hospitalizaciones_listar"),

    path("tratamientos/nuevo/", TratamientoNuevo.as_view(), name="tratamiento_nuevo"),
    path("tratamientos/editar/<int:pk>", TratamientoEditar.as_view(), name="tratamiento_editar"),
    path("tratamientos/borrar/<int:pk>", TratamientoBorrar.as_view(), name="tratamiento_borrar"),
    path("tratamientos/", TratamientoListar.as_view(), name="tratamiento_listar"),


    path("detalletratamientos/nuevo/<int:id>", DetalleTratamientoNuevo.as_view(), name="detalletratamiento_nuevo"),
    path("detalletratamientos/editar/<int:pk>", DetalleTratamientoEditar.as_view(), name="detalletratamiento_editar"),
    path("detalletratamientos/borrar/<int:pk>", DetalleTratamientoBorrar.as_view(), name="detalletratamiento_borrar"),
    path("detalletratamientos/listar/<int:id>", DetalleTratamientoListar.as_view(), name="detalletratamiento_listar"),
]

entvirt/script/proyecto_tarea/proyecto_tarea/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cha_app/", include(('cha_app.urls', 'app'), namespace='cha_app')),
]

entvirt/script/proyecto_tarea/cha_app/models.py
from django.db import models


class Vendedor(models.Model):
    nombres = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    apellidos = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(self.nombres, self.apellidos)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Vendedor, self).save()

    class Meta:
        verbose_name_plural = "Vendedores"


class Asegurado(models.Model):
    nombres = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    apellidos = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    direccion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    estado = models.BooleanField(default=True)
    fecha_nacimiento = models.DateField(null=False, blank=False)

    def __str__(self):
        return "{} {}".format(self.nombres, self.apellidos)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Asegurado, self).save()


class Poliza(models.Model):
    descripcion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    costo = models.FloatField(default=0)
    costo_extension = models.FloatField(default=0)
    valor_cobertura = models.FloatField(default=0)

    def __str__(self):
        return "{} ".format(self.descripcion.upper())


class Hospital(models.Model):
    descripcion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    direccion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "{}".format(self.descripcion.upper())


class ContratoPoliza(models.Model):
    id_poliza = models.ForeignKey('Poliza', on_delete=models.CASCADE, null=False)
    id_vendedor = models.ForeignKey('Vendedor', on_delete=models.CASCADE, null=False)
    id_asegurado = models.ForeignKey('Asegurado', on_delete=models.CASCADE, null=False)
    fecha_contrato = models.DateField(null=False, blank=False)
    fecha_inicio = models.DateField(null=False, blank=False)
    fecha_fin = models.DateField(null=False, blank=False)
    estado = models.BooleanField(default=True)

    class Meta:
        ordering = ["id_poliza"]
        verbose_name_plural = "Contratos"

    def __str__(self):
        return "{} - {} {}".format(self.id_poliza.descripcion, self.id_asegurado.nombres, self.id_asegurado.apellidos)


class Doctor(models.Model):
    nombres = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    apellidos = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )

    estado = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(self.nombres, self.apellidos)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Doctor, self).save()


class Familiares(models.Model):
    asegurado = models.ForeignKey('Asegurado', on_delete=models.CASCADE, null=False)
    nombres = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    apellidos = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    fecha_nacimiento = models.DateField(null=False, blank=False)
    estado = models.BooleanField(default=True)

    class Meta:
        ordering = ["nombres"]
        verbose_name_plural = "Asegurados"

    def __str__(self):
        return "{}{}{} ".format(self.asegurado.nombres, self.nombres, self.apellidos)


class Hospitalizacion(models.Model):
    doctor = models.ForeignKey('Doctor', on_delete=models.CASCADE, null=False)
    contrato = models.ForeignKey('ContratoPoliza', on_delete=models.CASCADE, null=False)
    hospital = models.ForeignKey('Hospital', on_delete=models.CASCADE, null=False)
    fecha_entrada = models.DateField(null=False, blank=False)
    fecha_salida = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Hospitalizaciones"

    def __str__(self):
        return "{} {} {} {} ".format(self.contrato.id_asegurado,self.hospital.descripcion,  self.fecha_entrada, self.fecha_salida)


class Tratamiento(models.Model):
    descripcion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Tratamientos"

    def __str__(self):
        return "{}".format(self.descripcion)


class DetalleTratamiento(models.Model):
    hospitalizacion = models.ForeignKey('Hospitalizacion', on_delete=models.CASCADE, null=False)
    tratamiento= models.ForeignKey('Tratamiento', on_delete=models.CASCADE, null=False)
    descripcion = models.CharField(
        max_length=100,
        blank=False,
        null=False
    )
    fecha = models.DateField(null=False, blank=False)
    costo = models.FloatField(default=0)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "DetalleTratamientos"

    def __str__(self):
        return "{}".format(self.descripcion)

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/contrato_list.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 70rem;">
    <div class="card-header">Listado de Contratos de Poliza</div>
    <div class="card-body">
        <table class="table table-hover">
          <thead>
              <th>Id</th>
              <th>Descripcion de Poliza</th>
              <th>Nombre del Asegurado</th>
              <th>Fecha de Contrato</th>
              <th>Fecha Inicial</th>
              <th>Fecha Final</th>
              <th>Estado</th>
              <th>Accion</th>
          </thead>
          <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.id_poliza.descripcion|upper }}</td>
                <td>{{ item.id_asegurado }}</td>
                <td>{{ item.fecha_contrato }}</td>
                <td>{{ item.fecha_inicio }}</td>
                <td>{{ item.fecha_fin }}</td>
                <td> {% if item.estado %}
                       Activa
                     {% else %}
                       Inactiva
                     {% endif %}</td>
                <td>
                  <a href="{% url 'cha_app:contrato_editar' item.id %}" class="btn btn-warning"><i class='far fa-edit'></i>
                  <a href="{% url 'cha_app:contrato_borrar' item.id %}" class="btn btn-danger"><i class='fa fa-minus-circle'></i>

                </td>
        </tr>
        {% endfor %}
          </tbody>
      </table>
    </div>
    <div class="card-footer">
        <a href="{% url 'cha_app:contrato_nuevo' %}" class="btn btn-primary">Nuevo Contrato</a>
  </div>
  
  </div>
{% endblock %}
{% block js_page %}
<script language="JavaScript">
    $(document).ready(function() {
        $('.table').DataTable();
    } );
</script>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/detalletratamiento_borrar.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Confirma</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        <h3>¿Borrar {{ obj.descripcion }} ?</h3>
        <button type="submit" class="btn btn-danger" >Si, Borrar</button>
        <a href="{% url 'app:detalletratamiento_listar' %}" class="btn btn-info">No, Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/detalletratamiento_list.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 60rem;">
    <div class="card-header">Listado de Tratamientos Aplicados </div>
    <div class="card-body">
        <table class="table table-hover">
          <thead>
              <th>Id</th>
              <th>Descripcion</th>
              <th>Accion</th>
          </thead>
          <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.descripcion }}</td>
                <td><a href="{% url 'cha_app:detalletratamiento_editar' item.id %}" class="btn btn-warning"><i class='far fa-edit'></i></a>
                    <a href="{% url 'cha_app:detalletratamiento_borrar' item.id %}" class="btn btn-danger"><i class='fa fa-minus-circle'></i></a>

                </td>
        </tr>
        {% endfor %}        
          </tbody>
      </table>
    </div>
  </div>
  <div class="card-footer">
    <a href="{% url 'cha_app:detalletratamiento_nuevo' %}" class="btn btn-primary"><i class='fa fa-plus-circle'></i>&nbsp;Nuevo</a>
</div>
  
  </div>
{% endblock %}

{% block js_page %}
<script language="JavaScript">
    $(document).ready(function() {
        $('.table').DataTable();
    } );
</script>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/doctor_form.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<form method="post">{% csrf_token %}
    <div class="card border-primary mb-3" style="max-width: 40rem;">
        <div class="card-header">Agregar Doctor</div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    Nombres:
                </div>
                <div class="col-lg-4 col-md-4">
                    <input type="text" name="nombres" maxlength="100" required="" id="id_nombres" class="form-control">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    Apellidos:
                </div>
                <div class="col-lg-4 col-md-4">
                    <input type="text" name="apellidos" maxlength="100" required="" id="id_apellidos" class="form-control">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    Estado:
                </div>
                <div class="col-lg-2 col-md-2">
                    <input type="checkbox" name="estado" id="id_estado" checked="">
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'cha_app:doctor_listar' %}" class="btn btn-primary">Cancelar</a>
        </div>
    </div>
    </div>
</form>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/hospital_borrar.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Confirma</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        <h3>¿Borrar {{ obj.descripcion }}?</h3>
        <button type="submit" class="btn btn-danger" >Si, Borrar</button>
        <a href="{% url 'app:hospital_listar' %}" class="btn btn-info">No, Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/hospital_form.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<form method="post">{% csrf_token %}
<div class="card border-primary mb-3" style="max-width: 30rem;">
    <div class="card-header">Agregar Hospital</div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-3">
                <label>Descripcion</label>
            </div>
            <div class="col-lg-9">
                {{ form.descripcion }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <label>Direccion</label>
            </div>
            <div class="col-lg-9">
                {{ form.direccion }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3"><label>Estado</label></div>
            <div class="col-lg-9">{{ form.estado }}</div>
        </div>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-success" >Guardar</button>
        <a href="{% url 'cha_app:hospital_listar' %}" class="btn btn-primary">Cancelar</a>
    </div>
 </div>
</form>

{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/hospitalizacion_form.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<form method="post">{% csrf_token %}
    <div class="card border-primary mb-3" style="max-width: 30rem;">
        <div class="card-header">Agregar Hospitalizacion</div>
        <div class="card-body">
            {{ form.as_p }}


        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'cha_app:hospitalizaciones_listar' %}" class="btn btn-primary">Cancelar</a>
        </div>
    </div>
</form>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/hospitalizacion_list.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 100rem;">
    <div class="card-header">Listado de Hospitalzaciones</div>
    <div class="card-body">
        <table class="table table-hover">
          <thead>
              <th width="50">Numero de Hospitalizacion</th>
              <th>TIpo de Poliza</th>
              <th>Asegurado</th>
              <th>Hospital</th>
              <th>Medico</th>
              <th>Fecha de Entrada</th>
              <th>Fecha de Salida</th>
              <th>Accion</th>
          </thead>
          <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.contrato.id_poliza }}</td>
                <td>{{ item.contrato.id_asegurado }}</td>
                <td>{{ item.hospital }}</td>
                <td>{{ item.doctor }}</td>
                <td>{{ item.fecha_entrada|date:'d/m/Y'}}</td>
                <td>{{ item.fecha_salida|date:'d/m/Y'}}</td>
                <td><a href="{% url 'cha_app:hospitalizaciones_editar' item.id %}" class="btn btn-warning"><i class='far fa-edit'></i></a>
                    <a href="{% url 'cha_app:hospitalizaciones_borrar' item.id %}" class="btn btn-danger"><i class='fa fa-minus-circle'></i></a>
                    <a href="{% url 'cha_app:detalletratamiento_nuevo' item.id  %}" class="btn btn-success"><i class='fa fa-stethoscope'></i></a>
                    <a href="{% url 'cha_app:detalletratamiento_listar' item.id  %}" class="btn btn-info"><i class='fa fa-align-justify'></i></a>
                </td>
        </tr>
        {% endfor %}        
          </tbody>
      </table>
    </div>
    <div class="card-footer">
        <a href="{% url 'cha_app:hospitalizaciones_nuevo' %}" class="btn btn-primary">Nueva</a>
  </div>
  
  </div>
{% endblock %}
{% block js_page %}
<script language="JavaScript">
    $(document).ready(function() {
        $('.table').DataTable();
    } );
</script>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/poliza_form.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<form method="post">{% csrf_token %}
    <div class="card border-primary mb-3" style="max-width: 40rem;">
        <div class="card-header">Agregar Poliza</div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    Descripcion:
                </div>
                <div class="col-lg-6 col-md-6">
                    {{ form.descripcion }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    Costo:
                </div>
                <div class="col-lg-6 col-md-6">
                   {{ form.costo }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    Costo x Extension:
                </div>
                <div class="col-lg-6 col-md-6">
                   {{form.costo_extension}}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    Valor de la Cobertura:
                </div>
                <div class="col-lg-6 col-md-6">
                    {{ form.valor_cobertura }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    Estado:
                </div>
                <div class="col-lg-6 col-md-6">
                    {{ form.estado }}
                </div>
            </div>

        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'cha_app:poliza_listar' %}" class="btn btn-primary">Cancelar</a>
        </div>
    </div>
</form>

{% if form.errors %}
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <h4 class="alert-heading">Warning!</h4>
                <p class="mb-0">
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    {{ error|escape}}
                    {% endfor %}
                    {% endif %}
                    {% endfor %}

                    {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    {{ error|escape}}
                    {% endfor %}
                    {% endif %}
                </p>
            </div>
            <br>
        </div>
    </div>
    {% endif %}

{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/tratamiento_borrar.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Confirma</div>
    <div class="card-body">
      <form method="post">{% csrf_token %}
        <h3>¿Borrar {{ obj.descripcion }} ?</h3>
        <button type="submit" class="btn btn-danger" >Si, Borrar</button>
        <a href="{% url 'app:tratamiento_listar' %}" class="btn btn-info">No, Cancelar</a>
    </form>
    </div>
  </div>
  
  </div>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/vendedor_form.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
      <form method="post">{% csrf_token %}
<div class="card border-primary mb-3" style="max-width: 20rem;">
    <div class="card-header">Agregar Vendedor</div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-3">
                <label>Nombres:</label>
            </div>
             <div class="col-lg-9">
                 {{ form.nombres }}
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <label>Nombres:</label>
            </div>
             <div class="col-lg-9">
                 {{ form.apellidos }}
            </div>
        </div>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-success" >Guardar</button>
        <a href="{% url 'cha_app:vendedor_listar' %}" class="btn btn-primary">Cancelar</a>
    </div>
  </div>
  
  </div>
</form>
{% endblock %}

entvirt/script/proyecto_tarea/cha_app/templates/cha_app/vendedor_list.html
{% extends 'base/home.html' %}

{% block contenido %}
<br>
<div class="card border-primary mb-3" style="max-width: 30rem;">
    <div class="card-header">Listado de Vendedores</div>
    <div class="card-body">
        <table class="table table-hover">
            <thead>
            <th>Id</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Accion</th>
            </thead>
            <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.nombres }}</td>
                <td>{{ item.apellidos }}</td>
                <td><a href="{% url 'cha_app:vendedor_editar' item.id %}" class="btn btn-warning"><i
                        class='far fa-edit'></i></a>
                    <a href="{% url 'cha_app:vendedor_borrar' item.id %}" class="btn btn-danger"><i
                            class='fa fa-minus-circle'></i></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <hr>
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li  class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
    <div class="card-footer">
        <a href="{% url 'cha_app:vendedor_nuevo' %}" class="btn btn-primary"><i class='fa fa-plus-circle'></i>&nbsp;Nueva</a>
    </div>
</div>

</div>
{% endblock %}